### ISSUE TITLE
Not work with min api 9

### ISSUE THREAD

**Issue by idemax** [keklikhasan/LDrawer#15]
Just don't work, the drawer icon is static with arrow icon.

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "my.app.package"
        minSdkVersion 9
        targetSdkVersion 21
        versionCode 11
        versionName "2.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.ikimuhendis:ldrawer:0.1'
}
```

**Comment by idemax** [comment]
I'm getting this error:

01-30 22:44:46.122      894-894/my.app.package
E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle﹕ setActionBarUpIndicator error
    java.lang.NullPointerException: null receiver
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.setActionBarUpIndicator(ActionBarDrawerToggle.java:130)
            at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.syncState(ActionBarDrawerToggle.java:57)
            at br.com.ngt.anotacoes.view.fragments.NavigationDrawerFragment$4.run(NavigationDrawerFragment.java:160)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by vijaykd** [comment]
Did this issue get solved? if so how? Do you have work around for this? I am getting issue for API 14 too.

**Comment by levelibeeka** [comment]
I'm having the same problem...

**Comment by levelibeeka** [comment]
see [https://github.com/ikimuhendis/LDrawer/issues/20](https://github.com/ikimuhendis/LDrawer/issues/20)
It works fine!

**Comment by salimkayabasi** [comment]
Using support library is quite basic solution. Sorry about that but this project is deprecated.
