### ISSUE TITLE
NoSuchMethodException

### ISSUE THREAD

**Issue by FongMi** [keklikhasan/LDrawer#3]
NoSuchMethodException: setHomeActionContentDescription [int]
            at java.lang.Class.getConstructorOrMethod(Class.java:460)
            at java.lang.Class.getDeclaredMethod(Class.java:685)
            at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.setActionBarDescription(ActionBarDrawerToggle.java:161)
            at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.syncState(ActionBarDrawerToggle.java:58)
            at com.fongmi.ticket.activity.Main.onPostCreate(Main.java:158)
            at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1145)
            at com.lbe.security.service.core.client.b.x.callActivityOnPostCreate(Unknown Source)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2398)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by smallzhan** [comment]
Same issue on an android 4.2.2 device but is ok on android 4.4.2

**Comment by keklikhasan** [comment]
You can use appcompat library now, i added note to  [README.md](https://github.com/ikimuhendis/LDrawer/blob/master/README.md#note)
