### ISSUE TITLE
NoSuchMethodException: setHomeActionContentDescription [int]

### ISSUE THREAD

**Issue by F1orin** [keklikhasan/LDrawer#7]
As far as I tested everything works, but when the Drawer is opened and closed such exception occurs:

``` java
10-23 20:09:38.992    1818-1818/<some_package> E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle﹕ setActionBarUpIndicator
    java.lang.NoSuchMethodException: setHomeActionContentDescription [int]
            at java.lang.Class.getConstructorOrMethod(Class.java:460)
            at java.lang.Class.getDeclaredMethod(Class.java:685)
            at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.setActionBarDescription(ActionBarDrawerToggle.java:161)
            at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.onDrawerOpened(ActionBarDrawerToggle.java:110)
            at ua.com.florin.anotherflashlight.MainActivity$2.onDrawerOpened(MainActivity.java:73)
            at android.support.v4.widget.DrawerLayout.dispatchOnDrawerOpened(DrawerLayout.java:587)
            at android.support.v4.widget.DrawerLayout.updateDrawerState(DrawerLayout.java:539)
            at android.support.v4.widget.DrawerLayout$ViewDragCallback.onViewDragStateChanged(DrawerLayout.java:1495)
            at android.support.v4.widget.ViewDragHelper.setDragState(ViewDragHelper.java:866)
            at android.support.v4.widget.ViewDragHelper$2.run(ViewDragHelper.java:335)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lazypixelIn** [comment]
I am Also Having Same problem btw can u tell me if it cause the force close or not

**Comment by F1orin** [comment]
I supposed that I did something wrong while implementing the drawer in my application, so I decided to check the sample application whether it has the same problem. I checked the logcat of the [sample application](https://play.google.com/store/apps/details?id=com.ikimuhendis.ldrawer.sample) on Galaxy I9500 and it reported the same exception thrown. So no doubt this is the issue of the library.

@parthnvs,  the sample application does not force close, but some manual testing of the application that I'm working on has shown that it force closes when you touch the area in the right of the drawer (the empty area when the drawer is opened) with the following exception:

``` java
10-24 14:52:47.732  26942-26942/<some_package> E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.support.v4.widget.DrawerLayout.isContentView(DrawerLayout.java:964)
            at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:990)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1909)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2270)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1967)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2270)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1967)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2270)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1967)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2270)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1967)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2182)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1512)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2466)
            at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.dispatchTouchEvent(ActionBarActivityDelegateICS.java:268)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2130)
            at android.view.View.dispatchPointerEvent(View.java:7641)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3682)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3613)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4804)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4783)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4875)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:125)
            at android.os.Looper.loop(Looper.java:124)
            at android.app.ActivityThread.main(ActivityThread.java:5328)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
```

The application's main activity has a container with fragment with ListView inside.

**UPD**: The application does not crash anymore. The problem was that I've put the `FrameLayout` container outside of the `DrawerLayout`. However, NoSuchMethodException problem remains.

**Comment by jamessg** [comment]
how did you do the icon animation, I didn't find it in sample application

**Comment by roxx** [comment]
I 'm also having the same Exception. The app. does not force close but in Logcat I'm receiving error log;
java.lang.NoSuchMethodException: setHomeAsUpIndicator
java.lang.NoSuchMethodException: setHomeActionContentDescription

Any solutions?

**Comment by leo2013** [comment]
setHomeAsUpIndicator
setHomeActionContentDescription
Both methods are added in API Level 18.
Check sdk build verision.

**Comment by aristide** [comment]
i'm having the folllowing error  when i tried to run the LDrawer sample project :scream: .  

```
  01-06 11:26:18.276  12516-12516/com.ikimuhendis.ldrawer.sample E/com.ikimuhendis.ldrawer.ActionBarDrawerToggle﹕ setActionBarUpIndicator
    java.lang.NoSuchMethodException: setHomeActionContentDescription [int]
            at java.lang.Class.getConstructorOrMethod(Class.java:460)
            at java.lang.Class.getDeclaredMethod(Class.java:685)
            at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.setActionBarDescription(ActionBarDrawerToggle.java:161)
            at com.ikimuhendis.ldrawer.ActionBarDrawerToggle.onDrawerClosed(ActionBarDrawerToggle.java:122)
            at com.ikimuhendis.ldrawer.sample.SampleActivity$2.onDrawerClosed(SampleActivity.java:51)
            at android.support.v4.widget.DrawerLayout.dispatchOnDrawerClosed(DrawerLayout.java:631)
            at android.support.v4.widget.DrawerLayout.updateDrawerState(DrawerLayout.java:611)
            at android.support.v4.widget.DrawerLayout$ViewDragCallback.onViewDragStateChanged(DrawerLayout.java:1632)
            at android.support.v4.widget.ViewDragHelper.setDragState(ViewDragHelper.java:873)
            at android.support.v4.widget.ViewDragHelper$2.run(ViewDragHelper.java:335)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4441)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
            at dalvik.system.NativeStart.main(Native Method)
```

How can i solve it? Any help??? :pensive:

**Comment by salimkayabasi** [comment]
Using support library is quite basic solution. Sorry about that but this project is deprecated.
